### ISSUE TITLE
move RDO instance to a new home

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#119]
The HACKING doc references and RDO image in stored in HP's cloud which will go away soon.  The RDO image should be moved to a longer lived location (maybe tcloud.solinea.com?), and the documentation should be updated to point developers at the new location.

HP cloud will become unavailable on Jan 31, 2016.

**Comment by lexjacobs** [comment]
Related to https://github.com/Solinea/goldstone-compliance/issues/21
