### ISSUE TITLE
Can't shut down and restart container with addons installed. (with branch change)

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#127]
To create this issue I:

Installed 2 addons.
Restarted the containers. Everything was working correctly.

With the addons installed, there are changes to:
![image](https://cloud.githubusercontent.com/assets/5633015/11286143/3da8938e-8ec8-11e5-9456-ba29e0f87977.png)

Then I needed to switch branches.
And in order to switch branches these changes have to be stashed.
I stashed the changes.
I stopped the container with 'control-c' and waited for it to stop.

Then I switched branches.
Then I did a git stash pop to put the files back that are related to the addons.

Then I started the containers again and the following errors were generated.
(attached text files).
I also tried stashing/stopping/changing branches to master/stash-popping.
The result of that bin/start attempt is the 2nd text file.

[addon-stop-start.txt](https://github.com/Solinea/goldstone-server/files/39506/addon-stop-start.txt)
[addon-stop-start2.txt](https://github.com/Solinea/goldstone-server/files/39507/addon-stop-start2.txt)

**Comment by jxstanford** [comment]
this should be fixed with the submodule approach.
