### ISSUE TITLE
Update ./bin/configure_stack.sh to use $PROJECT_HOME

### ISSUE THREAD

**Issue by jruels** [Solinea/goldstone-server#134]
In configure_stack.sh it assumes the user's goldstone-server is in ~/devel.  We should change this to a variable

`$PROJECT_HOME/goldstone-server`

**Comment by jxstanford** [comment]
`PROJECT_HOME` has some affiliation with virtualenv that I was trying to avoid in other scripts, so we have a different env var called `GS_PROJ_TOP_DIR`.  It defaults to `~/devel/goldstone-server`.  You can set it to match your directory structure, and all of the scripts should respect it.
