### ISSUE TITLE
docker entrypoint option to run tox tests inside container

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#135]
Document current process or add to script where necessary.

**Comment by heidecke** [comment]
What tests should be run on the final built containers? Are tox tests appropriate?

**Comment by jxstanford** [comment]
We would like to see successful runs of the following:
* `python manage.py test` or equivalent
* `pep8 --exclude=build,dist,.eggs,utils,migrations,.tox,doc/source/conf.py,node_modules/casperjs,node_modules/grunt-casper,docker/Dockerfiles/goldstone-app/goldstone-server .`

If this were a release build (master), that should be sufficient to create/push new images, and RPM/DEB builds.
