### ISSUE TITLE
Create CADF event from log message matching an ES query

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#146]

**Comment by bhuvan-rk** [comment]
1. A variety of sources send queries of all kinds to the Elastic-Search System  <Q0 to Qn-1>
2. For any Qi, if Qi matches the format of a standard log message we need to generate an Alert Ai (Example ES query matching a log format needed here)
3. This alert Ai needs to be in the standard CADF format in the ElasticSearch index data structure. 
4. This formatting can be applied via the Pycadf library

**Comment by jxstanford** [comment]
You will probably want to implement the concepts of Event Query and Alert Query separately.  In the design doc, they are referred to as EventDef and AlertDef.  The primary difference is the indices they operate on.  

Events are stored in ES as CADF-formatted docs (`git://git.openstack.org/openstack/pycadf`), Alerts should have a fixed structure, but I suspect CADF is too prescriptive.  The Alert data structure should reference the ID of the CADF event.

2) if an event query matches a log message, you will need generate an Event in CADF format.  If the event matches an

**Comment by bhuvan-rk** [comment]
Right. There a typo there. The text here is meant to be an Event and not an alert. Which is why #147 follows #146. 

Here is the re-worded #146

A variety of sources send queries of all kinds to the Elastic-Search System
For any Qi, if Qi matches the format of a standard log message we need to generate an Event Ei (Example ES query matching a log format needed here)
This Event Ei needs to be in the standard CADF format in the ElasticSearch index data structure.
This formatting can be applied via the Pycadf library

**Comment by bhuvan-rk** [comment]
So currently the only two types of standard log messages we support are these : 

from glogging/models.py : 
    LOG_EVENT_TYPES = ['OpenStackSyslogError', 'GenericSyslogError']

This is for the second step : 

For any Qi, if Qi matches the format of a standard log message we need to generate an Event Ei (Example ES query matching a log format needed here)

Is my assumption correct ?

**Comment by jxstanford** [comment]
Yes, we should convert those to protected "EventDefs" in the new implementation.  They should be able to provide you with the sample queries you were asking about above..

**Comment by bhuvan-rk** [comment]
Cool. Got it

**Comment by jxstanford** [comment]
The SavedSearch task that runs will create a CADF event with the count of matches for each search owned by 'events'.  The event is persisted to ES.
