### ISSUE TITLE
Create alerts from SavedSearch results

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#147]

**Comment by bhuvan-rk** [comment]
This issue flows from #146 

When an event Ei as described by #146 gets generated, that event can in-turn match a pre-set alert. These alerts can be both pre-defined or user-configured. 

TBD's ?
Can this alert be defined at run-time also ? If yes, do we also allow backward application of alert-triggers based on past events ? Since we do store it in the DB ?

Do we need to give knobs to turn-on or off such alerts ? Are these P0's or P1 items ?

Relevant text from the doc : 

An alert is generated by a query defined as part of an AlertDef resource.  AlertDef will be part of the core Goldstone Server model, and persisted in Postgres.  The query will be executed on a periodic schedule via a Celery task.  

Future enhancements to the AlertDef specification can consider folding correlated events into a single alert, or other conditional cases.

**Comment by bhuvan-rk** [comment]
This is the placeholder issue for designing and implementing Alert System Design

**Comment by jxstanford** [comment]
renamed issue to be more appropriate.

**Comment by bhuvan-rk** [comment]
https://docs.google.com/document/d/1qkLzo1hUaoJSIBW8vWB4FEIsAlDb4nF_jP1uFwcK4rY/edit
