### ISSUE TITLE
create a code-base tree document for dev reference

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#160]

**Comment by bhuvan-rk** [comment]
Assigning this forward to Alex to review and comment on the client files

**Comment by lexjacobs** [comment]
* General edits
* Linked from HACKING.md
* renamed to CODEBASE.md from codebase.md
* submitted PR

**Comment by bhuvan-rk** [comment]
Hi Alex, 

I want this to be passed around to John.D and/or John.S so that they can help shed some more light on our code-base org. So lets keep this one open for a while. 

Thanks
Bhuvana

**Comment by lexjacobs** [comment]
Got it. Thanks for clarifying.

**Comment by jxstanford** [comment]
can we close this ticket?
