### ISSUE TITLE
data volume containers are not getting cleaned up when dev env is stopped/killed

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#161]
This is a placeholder for @heidecke.  Please fill in the detail.

**Comment by jxstanford** [comment]
@heidecke you wanted me to file this thing.  Is it still relevant?

**Comment by heidecke** [comment]
Should be resolved by cleaning up the docker image creation to only include VOLUME where absolutely necessary. Will reduce the number of orphaned data volumes when recreating a stack.
