### ISSUE TITLE
create a code-flow document for Events and Alerts System design for review 

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#164]

**Comment by bhuvan-rk** [comment]
[EventQuery _ Code Flow Sequence .pdf](https://files.zenhub.io/5660d150c6baa4f214c44863)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jxstanford** [comment]
Looks good.  We should probably keep track of the last successful event generation cycle to provide a time box for the current cycle.

**Comment by bhuvan-rk** [comment]
How does one do that ?

**Comment by jxstanford** [comment]
You could create an internal event when you complete the query process.  When you're starting the next pass, you could look up the last successful event and use the timestamp to filter your query.  

That's an optimistic approach that doesn't take into account that logs could arrive late with timestamps that are before the last successful event, but that should be sufficient for MVP.

**Comment by jxstanford** [comment]
can we close this out yet?
