### ISSUE TITLE
inappropriate message to refresh browser

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#174]
I get this message immediately after refreshing the browser.  

![image](https://cloud.githubusercontent.com/assets/787382/11824141/d3159c00-a32c-11e5-8c5b-e3f7925be1a0.png)

The addons dropdown looks like this:

![image](https://cloud.githubusercontent.com/assets/787382/11824170/f994a308-a32c-11e5-8ad9-db54cf37fed2.png)

If I log out and log back in, the addon appears to be normal.  Perhaps that should be the message?

**Comment by lexjacobs** [comment]
Handled on #185

**Comment by lexjacobs** [comment]
Handled on #185
