### ISSUE TITLE
resolve where the help and issues links go for both versions of goldstone server

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#180]
![image](https://cloud.githubusercontent.com/assets/787382/11884343/127457b8-a4ce-11e5-9925-41d74c08d948.png)

help to docs or freshdesk faq?
issues to freshdesk or github?
etc...

**Comment by jxstanford** [comment]
issues should all go to freshdesk
help to freshdesk

**Comment by lexjacobs** [comment]
@jxstanford please assign ticket to me when resolved and I'll implement the change.

**Comment by jxstanford** [comment]
Would like the "help" icon to go to this link.  Let's also change the icon label to "Support":
    `https://solinea.freshdesk.com/support/home`

Would like the "Github" link to go to:
    `https://github.com/Solinea/goldstone-server`

Current panel for reference:
![image](https://cloud.githubusercontent.com/assets/787382/13398990/d5fb8f96-deb5-11e5-8932-d382f17cde3f.png)
