### ISSUE TITLE
css adjustments for overall page layout.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#183]
"Seems like we should shrink the right margin a bit (say by 50%) to get a more comfortable feel."

"when a browser alert is present, the right veritical menu should push down as well."

![image](https://cloud.githubusercontent.com/assets/5633015/11885778/85a83bec-a4d7-11e5-9555-f84813b7325f.png)

the latter is due to a known issue with LastPass:
https://forums.lastpass.com/viewtopic.php?f=12&t=77759

CSS 'absolute' positioning will need to be adjusted.

**Comment by lexjacobs** [comment]
* fix css settings for pop-up alerts at top of page. currently they are being overlaid by the z-index of 9999 on the sidebar menu.

**Comment by lexjacobs** [comment]
* firefox / chrome implementations of lastpass don't push page down equally.

firefox:

![image](https://cloud.githubusercontent.com/assets/5633015/11945689/6b991a72-a807-11e5-9eab-07b53bce3a9e.png)

**Comment by jxstanford** [comment]
Closing since this is an upstream issue.  Maybe some day Lastpass will fix and this will go away.
