### ISSUE TITLE
Intermittent errors in starting/stopping of containers.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#187]
Intermittent error when starting up with `bin/start_dev_env`
@bhuvan-rk  and @lexjacobs have both experienced this.
![pasted image at 2015_12_22 03_39 pm](https://cloud.githubusercontent.com/assets/5633015/11968831/5b4baaf4-a8c5-11e5-8dcd-31e88d1909fd.png)

Intermittent error when stopping containers with ^C
@lexjacobs reporting, so far no one else.
![pasted image at 2015_12_22 03_59 pm](https://cloud.githubusercontent.com/assets/5633015/11968830/5b4ab75c-a8c5-11e5-9a7b-630596dfff94.png)

**Comment by heidecke** [comment]
@bhuvan-rk @lexjacobs Would you please give some info on your environment to reproduce?

1. Docker machine version. `docker-machine -v`
2. Docker machine driver. `docker-machine ls`
3. Docker machine VM environment info. Run `docker-machine ssh $(docker-machine active)` and capture the Boot2Docker and Docker versions.

**Comment by heidecke** [comment]
It seems like the first error just means that you might not have set the docker env w/ `eval $(docker-machine env default)`. Do you have this in your .bashrc/.zshrc?

**Comment by lexjacobs** [comment]
Thanks. I'll try again with the docker env set as you mentioned above.

In reply to your first comment:

`docker-machine -v`
docker-machine version 0.5.0 (04cfa58)

`docker-machine ls`
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376


VM environment info:
Boot2Docker version 1.9.0, build master : 16e4a2a
Docker version 1.9.0, build 76d6bc9

**Comment by lexjacobs** [comment]
@heidecke 
Not sure how to set the docker env prior to starting the VM.
I get this error:

```
$ eval $(docker-machine env default)
Error running connection boilerplate: default is not running. Please start it in order to use the connection settings

```

**Comment by jxstanford** [comment]
`start_dev_env.sh` does the eval.  There may be a timing issue after it starts the docker machine VM.  It immediately tries to do the eval.  We probably just need to ensure that the VM has completed startup.

**Comment by jxstanford** [comment]
after further exploration, this seems to be an upstream problem between docker-machine and virtualbox.
