### ISSUE TITLE
py27 tests fail in ci, default addon-requirements.txt not present in repo

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#188]
```
Could not open requirements file: [Errno 2] No such file or directory: '/home/ubuntu/goldstone-server/addon-requirements.txt'
```

What is the preferred fix for this? Would rather not touch an empty file.

**Comment by jxstanford** [comment]
addons will be managed via git submodules going forward.  there is a PR going out for it as we speak.  The preferred approach will be to build the app container without the submodule installed, and the app-e container with.  No special handling of test suite will be required.
