### ISSUE TITLE
Add javascript testing and coverage to CircleCI

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#199]
Add the appropriate commands to CircleCI to run tests and coverage reports. Forward reports to codecov.io

Example: https://github.com/kt3k/codecov-karma-example/blob/master/README.md

**Comment by heidecke** [comment]
Will follow up with @lexjacobs this week for JS test commands.

**Comment by jxstanford** [comment]
Here are the commands.  The app server must be running:

```npm install (from the top of the repo) 
npm install -g grunt-cli
grunt lintAndTest```

**Comment by jxstanford** [comment]
Let's do this as a breakout at the offsite.

**Comment by heidecke** [comment]
```
dependencies:
  override:
    - npm install
    - npm install -g grunt-cli
```
