### ISSUE TITLE
migrate all subclasses of DailyIndexDocType to the implementation in new_models.

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#201]
will need to address the handling of raw fields as well as determine how best (if at all) to present aggregations of search data.  It may be easier to convert the existing implementations (EventData, MetricData, etc.) to subclasses of SavedSearch.

**Comment by jxstanford** [comment]
@lexjacobs here are three variants of response to the updated spawns API call:

No spawns ever:
`{"count":0,"next":null,"previous":null,"results":[]}`

No spawns in window:
`{"count":0,"next":null,"previous":null,"results":[],"aggregations":{"per_interval":{"buckets":[]}}}`

A successful spawn (no failures).  Note that if there are no failures/successes in the a bucket, that field will not be present:

```{"count":1,"next":null,"previous":null,"results":[{"_score":1.9162908,"_type":"nova_spawns","_id":"AVLCFtUMTT9wXzuqbiIw","_source":{"success":"true","syslog5424_host":"rdo-kilo","@timestamp":"2016-02-06T00:18:05.702Z","event":"finish","host":"rdo-kilo","@version":"1","received_at":"2016-02-08T18:13:41.796Z","type":"nova_spawns","port":34792},"_index":"goldstone-2016.02.06"}],"aggregations":{"per_interval":{"buckets":[{"success":{"buckets":[{"key":"true","doc_count":1}],"sum_other_doc_count":0,"doc_count_error_upper_bound":0},"key_as_string":"2016-02-06T00:18:00.000Z","key":1454717880000,"doc_count":1}]}}}```

**Comment by lexjacobs** [comment]
@jxstanford can you please provide an example of the structure of a return call that includes a failure?

**Comment by lexjacobs** [comment]
I managed to coerce some failures as shown by `nova list` by simultaneously spawning some `--flavor m1.xlarge` instances, but...

![image](https://cloud.githubusercontent.com/assets/5633015/12926606/17ac9392-cf19-11e5-8376-d8bbe43989bc.png)

... the call to /nova/hypervisor/spawns/ still shows 4 successes, 0 failures.

```
{
  "count": 4,
  "next": "http://localhost:8000/nova/hypervisor/spawns/?%40timestamp__range=%7B%22gte%22%3A1455039547748%2C%22lte%22%3A1455043147748%7D&interval=2.5m&page=2&page_size=1",
  "previous": null,
  "results": [
    {
      "_score": 4.7695713,
      "_type": "nova_spawns",
      "_id": "AVLHShDGg_1kSX18mQsd",
      "_source": {
        "success": "true",
        "syslog5424_host": "rdo-kilo",
        "@timestamp": "2016-02-09T18:27:44.018Z",
        "event": "finish",
        "host": "rdo-kilo",
        "@version": "1",
        "received_at": "2016-02-09T18:27:45.296Z",
        "type": "nova_spawns",
        "port": 50029
      },
      "_index": "goldstone-2016.02.09"
    }
  ],
  "aggregations": {
    "per_interval": {
      "buckets": [
        {
          "success": {
            "buckets": [],
            "sum_other_doc_count": 0,
            "doc_count_error_upper_bound": 0
          },
          "key_as_string": "2016-02-09T17:37:30.000Z",
          "key": 1455039450000,
          "doc_count": 0
        },
      
     [ ... ]
        {
          "success": {
            "buckets": [],
            "sum_other_doc_count": 0,
            "doc_count_error_upper_bound": 0
          },
          "key_as_string": "2016-02-09T18:30:00.000Z",
          "key": 1455042600000,
          "doc_count": 0
        },
        {
          "success": {
            "buckets": [
              {
                "key": "true",
                "doc_count": 2
              }
            ],
            "sum_other_doc_count": 0,
            "doc_count_error_upper_bound": 0
          },
          "key_as_string": "2016-02-09T18:32:30.000Z",
          "key": 1455042750000,
          "doc_count": 2
        },
        {
          "success": {
            "buckets": [
              {
                "key": "true",
                "doc_count": 1
              }
            ],
            "sum_other_doc_count": 0,
            "doc_count_error_upper_bound": 0
          },
          "key_as_string": "2016-02-09T18:35:00.000Z",
          "key": 1455042900000,
          "doc_count": 1
        }
      ]
    }
  }
}
```
