### ISSUE TITLE
call to /core/events/ no longer backfilling with empty buckets.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#217]
Interval is currently calculated to produce ~24 buckets on the events histogram.
When enough data exists in the db, it will do this.
The time between the requested 'greater than' time and the most recent actual event is being ignored.

This can be observed with the following calls.
15 min and 1 hour all had enough data to return the requested time ranges.
6 hours had a gap that was not backfilled.
1 day was able to reference to yesterdays data, but not a full day, so returned as much as was present.

terminal capture of api call and number of buckets in the result:

```
/core/events/?timestamp__range={"gte":1452274556469,"lte":1452275456469}&interval=37.5s  // (15 min)
bundle.js:3067 #of buckets:  24
bundle.js:3066 /core/events/?timestamp__range={"gte":1452271862605,"lte":1452275462605}&interval=150s // (1 hour)
bundle.js:3067 #of buckets:  25
bundle.js:3066 /core/events/?timestamp__range={"gte":1452253865885,"lte":1452275465885}&interval=900s // (6 hours)
bundle.js:3067 #of buckets:  6
bundle.js:3066 /core/events/?timestamp__range={"gte":1452189070920,"lte":1452275470920}&interval=3600s // (1 day)
bundle.js:3067 #of buckets:  19
bundle.js:3066 /core/events/?timestamp__range={"gte":1452189101939,"lte":1452275501939}&interval=3600s
bundle.js:3067 #of buckets:  19
```

same output screenshot:
![image](https://cloud.githubusercontent.com/assets/5633015/12205224/2465a914-b5ee-11e5-8b18-04aca036b7e8.png)

**Comment by jxstanford** [comment]
need to add `extended_bounds` parameter to `date_histogram` aggregation.

**Comment by jxstanford** [comment]
on the `logviewer-saved-search` branch
