### ISSUE TITLE
Create metric panel for dashboard

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#222]
design notes:
https://solinea.slack.com/files/jxstanford/F0GTT6RK4/metrics_overview_panel.pdf

**Comment by jxstanford** [comment]
*example query for the log data:*
`/core/logs/?@timestamp__range=\{"gte":1452731730365,"lte":1452732630365\}&interval=5m`

For the dot markers, add up the count of severities >= ERROR.  Would be nice to size the dot based on the count.

*example query for event data:*
`/core/events/?@timestamp__range=\{"gte":1452731730365,"lte":1452732630365\}&interval=5m`

For the dot markers, add up the count of outcome = 'failure (or failed)'.  Would be nice to size the dot based on the count.

*example query for API call data:*
`/core/api-calls/?@timestamp__range=\{"gte":1452731730365,"lte":1452732630365\}&interval=5m`

For the dot markers, add up the count of the range stats 400-499 + 500-599. Would be nice to size the dot based on the count.

**Comment by lexjacobs** [comment]
@jxstanford for the /core/events/ are you able to add the outcome (failure or failed) into the aggregations/per_interval/buckets results? they currently only have time and doc count. Please add outcome if possible.

**Comment by lexjacobs** [comment]
wip status:
fully functioning triple-line chart for api/events/logs with smooth transitions between updates.
hovering on dots brings up data of time/counts for metric at that point.

![image](https://cloud.githubusercontent.com/assets/5633015/12369716/8b631b4c-bbb1-11e5-93b2-0c0ebd9b7b65.png)


TODO:
* render more information about the underlying buckets in the popover dialogues.
* conditionally size the dots based on the underlying bucket information as outlined above.

**Comment by lexjacobs** [comment]
popovers dialogues updates to conditionally render contextual info.
dots sized based on underlying bucket info.
