### ISSUE TITLE
Service status - api call and chart.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#225]
Please create an api endpoint for:

![image](https://cloud.githubusercontent.com/assets/5633015/12212345/05a2bc8a-b61e-11e5-819e-8765e6ab3be2.png)

We need a call that does an aggregation of the API status calls per component.  The client will use this to represent service status via the following rules:

if there are no calls for a service, consider it suspicious and paint it grey
if there are no 2xx or 3xx calls for a service, consider it broken
otherwise consider it healthy

We will work on the definition of what makes a healthy service as we go further.

and reassign to @lexjacobs

**Comment by jxstanford** [comment]
neutron and glance do not appear to be putting events on the notification bus.  Will attempt to correct that.  The event formatting is also not as clean as I had hoped with respect to identifying the service that a message comes from.  Will probably take some fancy dancing in the serializer or view to normalize everything.

**Comment by jxstanford** [comment]
the HACKING and INSTALL docs need updates to reflect the name change of `configure_stack.py`

**Comment by jxstanford** [comment]
The API call for service status can be found by:

- GET /core/saved_search/?name=service+status
- GET /core/saved_search/{uuid of result above}/results/

The `per_component` aggregation has the data you will use.  You will need to maintain a reference list of expected components.  It is `[keystone, nova, neutron, glance, cinder]`.  If the count for a component is 0, the service is red, if > 0 the service is green, if not present, the service is gray.
