### ISSUE TITLE
/core/logs/ and /core/api-calls/ inconsistent with /core/events/

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#251]
Is it possible to make `timestamp__range=`  `/core/events/` into `@timestamp...`?

`/core/logs/` and `/core/api-calls/` both use `@timestamp__range...`
while `/core/events/` uses `timestamp__range`

**Comment by jxstanford** [comment]
unfortunately, we don’t have any control over the incoming events.  Most of them come directly from ceilometer into elasticsearch.  you did just make me realize that I have to add that field to our goldstone generated events though.
