### ISSUE TITLE
If no 'settings' present, redirect (or provide href link) to settings page.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#255]
TBD: perhaps upon login query an endpoint to verify settings.

Possibly: add file upload button to upload keystone file.

Also, remove table on http://localhost:8000/#settings/tenants page.
It will be a while before we support multiple tenants, and a table can be added then.

Reassigning to @jxstanford  per comment below

**Comment by jxstanford** [comment]
When implemented, then we can remove the process of configuring the openstack connection at install time.  pass the ticket back to me when ready.

**Comment by lexjacobs** [comment]
`bin/gscurl -p "http://localhost:8000/user/settings/"`
all 4 "os_" settings have to be present.
```
{
    "date_joined": "2016-02-13T00:23:23.292325Z",
    "default_tenant_admin": true,
    "email": "",
    "first_name": "",
    "is_superuser": false,
    "last_login": "2016-02-15T19:04:38.099187Z",
    "last_name": "",
    "os_auth_url": "http://172.24.4.100:5000/v2.0",
    "os_name": "admin",
    "os_password": "solinea",
    "os_username": "admin",
    "tenant_admin": true,
    "tenant_name": "default",
    "username": "gsadmin",
    "uuid": "33fce44f-6165-489a-a98b-aa3df14230ed"
}
```

**Comment by lexjacobs** [comment]
@jxstanford please provide a sample 'settings' file that a user might attempt to upload with the "upload settings file" button.

**Comment by jxstanford** [comment]
unset OS_SERVICE_TOKEN
export OS_USERNAME=admin
export OS_PASSWORD=12345
export OS_AUTH_URL=http://10.10.20.10:5000/v2.0
export PS1='[\u@\h \W(keystone_admin)]\$ '

export OS_TENANT_NAME=admin
export OS_REGION_NAME=RegionOne

**Comment by lexjacobs** [comment]
@jxstanford 
Call to /user/ only returns the following when logged in as 'admin'.

```
{
  "last_login": "2016-02-20T00:00:25.267904Z",
  "is_superuser": true,
  "username": "admin",
  "first_name": "",
  "last_name": "",
  "email": "dd@dd.com",
  "date_joined": "2016-02-17T18:54:45.619386Z",
  "tenant_admin": false,
  "default_tenant_admin": false,
  "uuid": "6ad2c544-b7ed-4771-95ac-61a53adfde7d"
}
```

please describe the criteria for determining if a redirect to '/#settings' is required in that case.

Also , UI doesn't support inputting changes to `os_*` fields.
Current UI is as follows:

![image](https://cloud.githubusercontent.com/assets/5633015/13193772/67f9837e-d733-11e5-81fd-97d6e15e3ad9.png)

**Comment by jxstanford** [comment]
settings are under the cloud API endpoint, and in the UI show up under the tenant settings if you are logged in as the goldstone admin (gsadmin).
