### ISSUE TITLE
Wire up events/api saved search dropdowns so they trigger a chart refresh.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#282]
Similar to the logBrowser viz which has a saved search dropdown, the api/events browsers have the same functionality via their own saved search dropdowns.

Hook them up so that a user selecting a saved search will trigger a chart refresh that reflects their saved searches.

**Comment by lexjacobs** [comment]
> If you're concerned about whether the search is well formed and has the right aggregation to draw the chart, don't be. Consider this MVP. We'll work on validation both on the front/back. For now, assume that the search will:
> a) be well formed with proper aggregation
> b) be bell formed without aggregation (maybe then put a popup alert in the chart: "No chart data defined in search"
> c) be poorly formed and you will get an error response back from server, then show a popup alert and go back to the default search.
> 
> To test each scenario:
> 
> a) take query from any of existing searches that works, and save it as a new one.
> b) same as above, but remove the aggs block
> c) use {} as the query

**Comment by jxstanford** [comment]
after discussion with @lexjacobs determined that it would be more efficient to do this during this sprint.  re-estimated to 2 based on log browser lessons learned.
