### ISSUE TITLE
Vulnerability advisor : change notice_date to date-time field from string 

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#288]
Extends from #274

**Comment by bhuvan-rk** [comment]
@lexjacobs I've checked in the changes to the following submodule and main branches. Feel free to test and verify :)

[goldstone-compliance:issue-274] 1 new commit by Bhuvana Ramkumar:
fcb830e: Changes to convert notice_date from string to datetime object. Corresponding changes to test, tasks and models - Bhuvana Ramkumar

[12:47] 
[goldstone-server:main_issue_274] 1 new commit by Bhuvana Ramkumar:
f54fdaf: Compliance : Changes to convert notice_date from string to datetime object. Corresponding changes to test, tasks and models - Bhuvana Ramkumar

**Comment by lexjacobs** [comment]
Merged 69b8f70c9727c45659070757a7b5efb97707224a
