### ISSUE TITLE
Convert index-prefix into a choice-field in SavedSearch

### ISSUE THREAD

**Issue by bhuvan-rk** [Solinea/goldstone-server#290]
Currently index-prefix is a simple string indexing into ElasticSearch. But AlertSearches are going to be targeted at both ElasticSearch, for index-based searching and at the ProstGresDB, for field-based searching. We want index_prefix to reflect this. 

So lets convert index_prefix into a ChoiceField object called record_type which will map to one of {vulnerabilities, logs, events, api-calls }. 

Correspondingly the AlertSearchSQL and AlertSearchES subclasses will be mapped based on where the data resides, via the record_type field.

**Comment by jxstanford** [comment]
need some sort of custom search editor.  falls under UI design topic.
