### ISSUE TITLE
PATCHing over protected search returned 200

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#291]
System should not allow a user to edit via PATCH to `/core/saved_search/uuid/` for an entity with `protected:true`.

![image](https://cloud.githubusercontent.com/assets/5633015/12656466/4acb332e-c5b3-11e5-8652-92773710945a.png)

shown below: I was able to change the name to 'stack tracesz'

![image](https://cloud.githubusercontent.com/assets/5633015/12656469/5290187c-c5b3-11e5-8829-8996e2514185.png)

Small update to client handling of error message.

**Comment by jxstanford** [comment]
@joraldaz we use Django Rest Framework for the API.  When a user calls PUT, PATCH or DELETE on the /core/saved_search/{uuid}/` API endpoint, they should get a HTTP 403 error back if the `protected` field in the model is `True`.
  
In `goldstone/core/views.py` there is a class called SavedSearchViewSet that handles all of this.  To address this ticket, you override the appropriate methods from ModelViewSet and do a check of the `protected` field before performing the requested action.
