### ISSUE TITLE
CPU, Memory, Storage X-axis legend unreadable

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#295]
On my macbook (_6hr lookback, 30s refresh_) the x-axis on the front page graphs are unreadable.

Perhaps there should only be 2 graphs per line ?

<img width="548" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12662115/616f8e6e-c661-11e5-9ae2-d81819a1b403.png">

**Comment by lexjacobs** [comment]
Fixed and out for PR on 'saved-search-client'
