### ISSUE TITLE
Clicking on goldstone logo leads to topology page instead of cockpit

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#296]
Clicking here ...

<img width="184" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12662235/41d9afe8-c662-11e5-8307-2f176b735763.png">

Leads to here ...

<img width="393" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12662245/592ec80e-c662-11e5-8a5b-0555d6d06b32.png">

instead of the front page.

**Comment by lexjacobs** [comment]
One line fix in process and will be committed to 'saved-search-client'
which is out for PR now.
