### ISSUE TITLE
service status icons should be centered

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#297]
I think that these icons should be centered under "status" ...

<img width="97" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12663842/9c2c7550-c66e-11e5-9100-136880bebf17.png">

**Comment by lexjacobs** [comment]
Fix checked into `saved-search-client` which is out for PR now.

![image](https://cloud.githubusercontent.com/assets/5633015/12664428/4d5ddeda-c5e4-11e5-920a-f9b2a09a735a.png)
