### ISSUE TITLE
Missing Japanese translations for some heading on front page 

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#298]
We are missing some Japanese translations on the front page ... in red

![image](https://cloud.githubusercontent.com/assets/9674/12664672/f40cc954-c674-11e5-962f-f5be6316e7d5.jpg)

**Comment by lexjacobs** [comment]
@slashk , CPU was the supplied translation for CPU.
A request for the translation of "Metric Overview" was sent to @takahigashi
who has been very busy with other projects so it probably got overlooked.
If you are working with him perhaps you can revisit the request.

**Comment by lexjacobs** [comment]
Will be handled in #292
