### ISSUE TITLE
API should be capitalized

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#300]
I think API should be capitalized on the API browser page.

<img width="275" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12668400/8022cafa-c699-11e5-8797-3085f29b851b.png">

**Comment by lexjacobs** [comment]
commit: 55764f41f checked into saved-search-client branch which is out for PR.
Normalized capitalization throughout site, and updated .po files.
