### ISSUE TITLE
event browser does not sort columns

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#301]
The event browser (`http://goldstoneip:8888/#reports/eventbrowser`) does not allow the table to be sorted by column. Using Chrome 48.0.2564.82 (64-bit) on Mac.

<img width="592" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12668520/d7ec0a8e-c69a-11e5-8ac4-4c8ba2757167.png">

**Comment by slashk** [comment]
![log-does-not-sort](https://cloud.githubusercontent.com/assets/9674/12699621/e17fc106-c804-11e5-9d5e-b3b8b1708656.gif)

**Comment by lexjacobs** [comment]
Sorting not supported via backend at this time.

`/core/api-calls/?@timestamp__range={%22gte%22:1454533307122,%22lte%22:1454534207122}&page_size=10&page=1&ordering=@timestamp`
or
`/core/api-calls/?@timestamp__range={%22gte%22:1454533403822,%22lte%22:1454534303822}&page_size=10&page=1&ordering=host`
or any other `ordering` field tested
return `results=[]`

Removed UI suggestion of sort functionality. Reassigning ticket.
Will return client sort elements when sorting is available.

**Comment by lexjacobs** [comment]
Will be handled in 344
