### ISSUE TITLE
No version information shown 

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#302]
Goldstone should expose its version number so that bugs can be reported more accurately.

Perhaps the bottom of the page could have the current version number installed.

<img width="611" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12668584/69bf7c84-c69b-11e5-95e3-0763a83a8b83.png">

**Comment by jxstanford** [comment]
@lexjacobs plz branch and update base.html and login.html templates to center the Copyright statement, and left align a `Version: {{ goldstone_version }}` statement.

**Comment by lexjacobs** [comment]
client fix pushed to `saved-search-client` PR as commit 4ee7cb1 "Add 'Version: {{ goldstone_version }}' to footer for login and base.html"

**Comment by jxstanford** [comment]
maybe put the details in a tooltip/hover
