### ISSUE TITLE
vulnerability advisor - server - enable search.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#308]
http://localhost:8000/#compliance/vulnerability/advisor/ currently has a search box. Please implement search serverside, or advise removal of search box client side.

**Comment by jxstanford** [comment]
probably need to add a custom regex filter for fields.  see: http://www.django-rest-framework.org/api-guide/filtering/

**Comment by lexjacobs** [comment]
Disabling search field on client pending backend support for search.

**Comment by lexjacobs** [comment]
duplicate of  https://github.com/Solinea/goldstone-compliance/issues/55
