### ISSUE TITLE
Expanding the side panel doubles the gutter

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#311]
Expanding the side panel to show the component names seems to triple the gutter between the side panel and the front page graphs. This results in the right side of the page getting pushed off the screen. The gutter should stay the same width regardless of the side panel setting.

<img width="471" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12694061/7ca423d6-c763-11e5-9045-32c0d67e888a.png">

<img width="471" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12694063/82236240-c763-11e5-88e5-4e8b26f5a761.png">

**Comment by joraldaz** [comment]
there is an issue with menu text on menu extend action to show up with a delay

**Comment by joraldaz** [comment]
Format sass files to use the nesting ability

**Comment by joraldaz** [comment]
@lexjacobs would be necessary a fix for the footer since it doesnt look quite right on small browser widths?

**Comment by joraldaz** [comment]
Added a page min-width
