### ISSUE TITLE
Information / setting icons for graphs should match design spec

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#312]
The original design used smaller and greyed out icons for graph settings and information.

![main_screen_expanded_menus_new_refresh](https://cloud.githubusercontent.com/assets/9674/12694256/9cee9c8c-c76a-11e5-852b-becb7eb6bb49.png)

It should look something more like this:

<img width="152" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12694271/b43bf186-c76b-11e5-8780-7f2cff134fb2.png">

**Comment by jxstanford** [comment]
not complete across site.
