### ISSUE TITLE
VM Spawns should always show graph even if there are no spawns

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#313]
The VM spawn graph on `http://goldstone/#discover` should always show a graph, even if it's a flat line of zeros.

<img width="144" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12694528/09cccce4-c774-11e5-8709-d624f33938bf.png">

**Comment by lexjacobs** [comment]
@jxstanford is there a "quick" fix in the backend that can return the `per_interval` results as all zeros if no spawn activity has ever been undertaken?

Here is what the result look like after spawn activity has occurred, but is not in the lookback range:

```
{
    "per_interval": [{
        "1454536080000": {
            "count": 0,
            "success": []
        }
    }, {
        "1454536140000": {
            "count": 0,
            "success": []
        }
    }, {
        "1454536200000": {
            "count": 0,
            "success": []
        }
    },
[...]
 {
        "1454536980000": {
            "count": 0,
            "success": []
        }
    }]
}
```

**Comment by jxstanford** [comment]
no real quick fix.  if ES doesn’t have data, it won’t generate the buckets.  seems like the quick fix is to render the axes regardless of the data.  probably just want the labels and axis lines, no ticks or values necessary.  That should make it easier.

**Comment by lexjacobs** [comment]
Our for PR here:
https://github.com/Solinea/goldstone-server/pull/337

**Comment by lexjacobs** [comment]
@jxstanford picking up this ticket starting Tuesday am, while "log browser triage" is out for PR.
