### ISSUE TITLE
predefined search dropdown misaligned

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#314]
Browser at 100% zoom.  Compliance module not installed.  Gear styling should match design spec (see @slashk comment on other charts).

![image](https://cloud.githubusercontent.com/assets/787382/12697472/4e0f141a-c739-11e5-8012-afb2b6901a47.png)

**Comment by lexjacobs** [comment]
@jxstanford 
gear modified to match spec.
Have you seen this issue arise again?
Since it's been migrated away from compliance, it should occur again.
Okay to close ticket?
