### ISSUE TITLE
Occassional DataTables warning

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#320]
Occasionally, after using the log viewer for a while, I'll get this warning/error dialog box.

<img width="593" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12710966/e4f1f142-c8fe-11e5-9211-011467abd3db.png">

**Comment by lexjacobs** [comment]
This should be handled now that ticket #211 was closed.
That ticket tidied up the saved search dropdown integration that was implemented in a rushed manner for the CTC demo deadline. 211 resulted in the proper architecture and testing, and the set of random errors you were encountering should be eliminated. 
I will keep an eye out for additional popup warnings, and please do report if it continues.
