### ISSUE TITLE
Duplicate fields in Event Browser?

### ISSUE THREAD

**Issue by slashk** [Solinea/goldstone-server#321]
Are `initiator_host_addr` and `initiator_host_address` actually different fields ?

Or are some events being truncated on that field header ?

They never seem to appear in the same event, which leads me to believe they should be combined in our storage / output.

<img width="533" alt="goldstone" src="https://cloud.githubusercontent.com/assets/9674/12711007/4572d8ce-c8ff-11e5-9582-dc6dc7787a89.png">

**Comment by jxstanford** [comment]
This is probably an upstream issue where different events are using different names.  We can file the upstream issue and it may eventually fix ours.

**Comment by jxstanford** [comment]
Upstream issue.
