### ISSUE TITLE
Popup hint is not translated in to Japanese

### ISSUE THREAD

**Issue by takahigashi** [Solinea/goldstone-server#329]
In Icon Only mode of side bar menu, popup hint appears for mouse over.
Those hints are not translated into Japanese.
If sidebar menu expanded, it appears Japanese label.

![sidebar](https://cloud.githubusercontent.com/assets/15721449/12742140/5fb1bc42-c9c6-11e5-8b03-ba648e495a51.jpg)

**Comment by lexjacobs** [comment]
Will be handled in #292
