### ISSUE TITLE
i18n stuff, including: Predefined Search setting screen is not translated, not use translated resources.

### ISSUE THREAD

**Issue by takahigashi** [Solinea/goldstone-server#332]
Setting of predefined search at report scree is not translated.
Also, default items appears in screen are also not translated.

![image](https://cloud.githubusercontent.com/assets/15721449/12742410/ca91be66-c9c8-11e5-9271-f9821fa37f28.png)

I also would like to suggest default items have description or search strings to make customers understand what the default item do.

**Comment by lexjacobs** [comment]
Assigning @jxstanford re: adding default descriptions.

**Comment by jxstanford** [comment]
I will add descriptions of saved searches, @lexjacobs will add the static text to i18n Japanese request for @takahigashi

**Comment by jxstanford** [comment]
ready for @lexjacobs  to add static text to PO files

**Comment by jxstanford** [comment]
sounds like @takahigashi might have some time on Friday (3/4) to do a bit more translation.  Can always pick this up a little later if necessary.

**Comment by lexjacobs** [comment]
i18n Japanese.po completed. Remaining steps: add new translations. Normalize English.po file against Japanese.po file.
