### ISSUE TITLE
Topology, resource list tutorial is not translated

### ISSUE THREAD

**Issue by takahigashi** [Solinea/goldstone-server#333]
Just after clicking topology of sidemenu, no component is selected and resource area display tutorial.
It is not translated and English appears.

![image](https://cloud.githubusercontent.com/assets/15721449/12742813/4e089000-c9cc-11e5-9307-7d1862051282.png)

**Comment by jxstanford** [comment]
@takahigashi can you provide the translation?

**Comment by lexjacobs** [comment]
Will be handled in #292
