### ISSUE TITLE
table sorting (tables with ES backend (api, event, log))

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#343]
Log browser should be able to sort on Timestamp, Syslog Severity, Component, Host, and Message.  Sorting should be performed server-side.

First place to look is applying a sort key to SavedSearches.  

**Also hit the event and API tables.**

**Comment by slashk** [comment]
I'm seeing this too ...

<img width="640" alt="fullscreen_2_6_16__4_42_pm" src="https://cloud.githubusercontent.com/assets/9674/12870240/afb1c340-ccf0-11e5-9213-9574875da222.png">

**Comment by lexjacobs** [comment]
Yep, additional saved searches were added after the last round of .po edits. They will be added when the scheduled i18n ticket is handled.

**Comment by lexjacobs** [comment]
@jxstanford 
Adding the `ordering` keyword in the server query returns [];
Is there a different keyword for sorting on the log/event/api tables?
If backend changes are needed, feel free to commit to the ''datatable-sorting-log-event-api" branch.




```
"http://localhost:8000/core/logs/?@timestamp__range={"gte":1457132413685,"lte":1457133313685}&interval=45s&syslog_severity__terms=["emergency","alert","critical","error","warning","notice","info","debug"]&page_size=10&page=1&ordering=-@timestamp"
```
returns []

**Comment by jxstanford** [comment]
@lexjacobs you should be able to use ordering=-field or ordering=field query parameters now.  If a field can not be sorted on, you will get an error back. It will be cryptic :-) 

Examples of working calls:
* `http://localhost:8000/core/api-calls/?ordering=-response_length`
* `http://localhost:8000/core/events/?ordering=-outcome`
* `http://localhost:8000/core/logs/?ordering=-log_message`

Example of calls that don't work:
*  `http://localhost:8000/core/logs/?ordering=message`
