### ISSUE TITLE
event browser table sorting

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#344]
Event browser should be able to sort on all fields.

**Comment by slashk** [comment]
i think this is a duplicate of issue #301

**Comment by lexjacobs** [comment]
This ticket came from a conversation on Friday about specific data table ui features that should exist for each table. I'll close #301, as non functioning ui elements in the datatables were shut off in some work that was just merged to master.

**Comment by jxstanford** [comment]
duplicate of #343
