### ISSUE TITLE
goldstone.events.tasks.log_event_search task does not properly serialize

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#346]
In the event browser, the  observer, target, initiator fields show up as `[object Object]`

**Comment by lexjacobs** [comment]
Observer/target/initiator can, as an interim solution, be shown in the table as one of the embedded properties (id/name/typeUri) by setting a conditional on rendering data with one of those keys.

[object Object] as likely suspected is the browser's fallback for toString()-ing the JSON object.

![image](https://cloud.githubusercontent.com/assets/5633015/12860808/ec021832-cc13-11e5-9864-60fc48829648.png)

**Comment by jxstanford** [comment]
I’m not sure the fields are all always guaranteed to be there.  I’d say flatten them out into their own columns of observer TypeURI and observer ID.  You might also see an observer name in there.  Might want to do that on the backend so that we can better handle searching/sorting.

**Comment by lexjacobs** [comment]
+1 for backend handling to support search/sort.

**Comment by jxstanford** [comment]
this task was removed.
