### ISSUE TITLE
enable SSL on nginx web server

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#374]
The web server should be configured to use SSL with either a self-signed cert or with a cert provided during the docker container build.  If provided by the builder, the cert files should be placed in the docker/goldstone-web/config folder, and handled properly by the Dockerfile and/or entrypoint script.

**Comment by jxstanford** [comment]
Here's a nice tutorial:  

https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04

Should also redirect the HTTP port to HTTPS.  That doesn't seem to be the case with the tutorial configuration.  But is covered here:

https://bjornjohansen.no/redirect-to-https-with-nginx

**Comment by jxstanford** [comment]
@jbc0 let me know if you need anything.  The script will eventually exist in docker/goldstone-web folder.  Environment variables should be put in docker/config/*.env.  We should probably include a 'none' option.

**Comment by jbc0** [comment]
I'm calling defeat on Letsencrypt - the domain validation is too much of an ask as a prerequisite and cumbersome to automate on a machine that isn't Internet exposed. I have a simple self-signed cert working from the container build. Just have a couple of deploy scenario questions unrelated to this issue.
