### ISSUE TITLE
uninstalling goldstone enterprise RPM does not remove docker images

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#384]
When I tried to yum uninstall 0.8.3, the docker containers were not shut down, and the images could not be removed.  Uninstallation should ensure that the containers are stopped, and the images are fully removed from the system.

**Comment by itlinux** [comment]
You can try this if you know all the package 

rpm -e --force package name or
rpm -e --nodeps package name or 
rpm -e --nodeps --force package name

Remo 

Inviato da iPhone

**Comment by jxstanford** [comment]
@itlinux I didn't dig into it, but I think that this is just a case of the docker containers not being stopped in the uninstall script.  The RPM does get uninstalled, but the containers are images are still on the system.

**Comment by itlinux** [comment]
Ok 

Inviato da iPhone
