### ISSUE TITLE
Language selection in setting should use native language always

### ISSUE THREAD

**Issue by takahigashi** [Solinea/goldstone-server#399]
![image](https://cloud.githubusercontent.com/assets/15721449/13519092/9265caf2-e217-11e5-9e9b-af298a02620b.png)

The selection of language may always use the native language what eve the current language set up is.
"English" for English, "日本語" for Japanese, "汉语“ for Simplified Chinese.
For now, I see "Japanese" for Japanese language at both English and Japanese mode.
It should appear as "日本語" for both English and Japanese mode.

I have filed this bug because I did not find language resource having "Japanese" as value. So I assume it is now hard coded.

**Comment by takahigashi** [comment]
Here is a example how language setting appears.
![image](https://cloud.githubusercontent.com/assets/15721449/13521645/89b2b3be-e22d-11e5-9a68-2d0cdff1ccb0.png)

**Comment by lexjacobs** [comment]
Thanks.
The language will appear in the list exactly as it is saved as a .po file.
At the moment it is saved as Japanese.po.
I will rename the file 日本語.po and that will fix the issue.

**Comment by lexjacobs** [comment]
done. will be committed to repo after PR is accepted. 

commit f611325e9328adeaef454208209e07fa75b3e6ee

![image](https://cloud.githubusercontent.com/assets/5633015/13536455/cef04eca-e1f4-11e5-99d1-e6292039e770.png)

**Comment by takahigashi** [comment]
Great! Thanks!!
