### ISSUE TITLE
Nits

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#419]
fine toothed comb

**Comment by lexjacobs** [comment]
@jxstanford please specify your preference for the formatting of an alert.

![image](https://cloud.githubusercontent.com/assets/5633015/13753803/c7780ebe-e9d1-11e5-93ec-3993d6740060.png)

**Comment by jxstanford** [comment]
For now, let’s remove the localized date and keep the one in the alert message.

**Comment by lexjacobs** [comment]
Handled prior to release of 1.0
