### ISSUE TITLE
alert panel should have a close icon

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#424]
I found it a little unintuitive to click the alert button again to close the alert popover.  Maybe we could leave that interaction in place, but also add an X to close it. 

![image](https://cloud.githubusercontent.com/assets/787382/13795277/4b13dae6-eabd-11e5-9d2f-1e2580b3e341.png)

**Comment by lexjacobs** [comment]
Got it. Will do.

**Comment by slashk** [comment]
How about a ⬅ or something like it instead ? something that says "put this back" ?
I find the (x) out of place ... it usually means "close this modal window" instead of push the drawer back.

**Comment by jxstanford** [comment]
@slashk works for me.
