### ISSUE TITLE
alert icon stays red after all alerts have moved out of "recent" state

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#436]
@lexjacobs the fix for 1.1 should be to explicitly set the state of the alert icon to on if there are recent alerts (last 24 hours), or off if there are no recent alerts.  That should pick up the case where alerts roll out of the recent time window.

-- old notes
it seems strange to see the red icon, click on alerts, then see nothing.  We could do a couple different things.  The easiest would be to un-highlight the alert icon if there are no recent alerts (last 24 hours).  

Beyond that, we might want to keep track of alert 'seen' state.  That get's a bit tricky when you extend to multi-tenant, but if we maintain a per-user state variable that tracks the last time they looked at the panel, we could use that to slice the data into recent and all columns.  

Thoughts?

**Comment by lukecongdon** [comment]
Certainly makes sense to not show it as red if no recent alerts are
present. Is the threshold for "current"=24hours? Once we have a UX resource
in house, I'll want to work on improved UX for zero states.

I think we could defer on the 'seen' state for now.

On Mon, Mar 28, 2016 at 8:36 AM, John Stanford <notifications@github.com>
wrote:

> @slashk <https://github.com/slashk> it seems strange to see the red icon,
> click on alerts, then see nothing. We could do a couple different things.
> The easiest would be to un-highlight the alert icon if there are no recent
> alerts (last 24 hours).
>
> Beyond that, we might want to keep track of alert 'seen' state. That get's
> a bit tricky when you extend to multi-tenant, but if we maintain a per-user
> state variable that tracks the last time they looked at the panel, we could
> use that to slice the data into recent and all columns.
>
> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Solinea/goldstone-server/issues/436>
>



-- 
Luke Congdon
Senior Director, Product Management
lcongdon@solinea.com
408.398.5517

**Comment by jxstanford** [comment]
Great.  I'll edit the description of this bug accordingly, and we can revisit as part of design.

**Comment by slashk** [comment]
is it "recent" or "unacknowledged" alerts that we want to turn the icon red?

**Comment by jxstanford** [comment]
We don’t currently have the concept of acknowledgement of an alert in the system.

**Comment by lexjacobs** [comment]
- when first loading goldstone, if there are not any alerts that would show up in the 'recent' column, then do not highlight the alert icon.

- use logic similar to the 'extractRecentAlerts' function to determine if there are new alerts when initially rendering the page.

- add test cases to 'test/integration/alertsMenuView_integrationTests.js'.

**Comment by jxstanford** [comment]
@joraldaz @lexjacobs has this been completed, or still a work in progress?

**Comment by lexjacobs** [comment]
@jxstanford per jor, work in progress.
