### ISSUE TITLE
Ceilometer event publishing bug with UDP

### ISSUE THREAD

**Issue by jbc0** [Solinea/goldstone-server#438]
Currently the integration fab script adds UDP publishers to the Ceilometer pipeline for forwarding events to Logstash, eg:
`udp://10.10.10.27:5516`

This triggers a bug in Ceilometer that is fixed in Mitaka by accident (no more eventlet) but it appears there is no fix for prior releases:
https://bugs.launchpad.net/ceilometer/+bug/1370459
The bug appears to cause event loss. (whether that is 100% or 10% needs to be determined)

According to docs, if `udp` is unusable then the only alternatives are `notifier` (AMQP), `file`, and `kafka`:
http://docs.openstack.org/admin-guide-cloud/telemetry-data-retrieval.html#publishers

Possible solutions might be configuring Logstash to ingest from Rabbit, or perhaps using `file` to output to fifo and have rsyslog forward that with UDP.

**Comment by jbc0** [comment]
For testing/debugging purposes: changed all the `udp://10.10.10.27:5516` to `notifier://?topic=goldstone`
and bound this ceilometer topic to `goldstone.event` fanout exchange (binding shown below).

Result: no more UDP send failures. 

Tested with a small python client to pull messages from goldstone_event and forward to logstash via UDP - ran into an issue with datagram size. Maybe somehow related to the original errors?
Also: rsyslog in CentOS is obsolete v7: no rabbitmq input mech.
Thoughts on other possible ingest methods for logstash?

![screen shot 2016-03-29 at 4 01 31 pm](https://cloud.githubusercontent.com/assets/591092/14100639/e67ef2ec-f5c9-11e5-8b8b-2b16589c168e.png)

**Comment by jxstanford** [comment]
We don't use the metrics anymore, so I think we can simply remove the template for pipeline.yaml that has the offending setting.
