### ISSUE TITLE
develop logstash patterns for RFC5424 formatted messages

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#446]
From Kilo to Liberty, the default logging behavior has changed (for the better).  It now uses RFC5424 formatted log lines, so instead of something like this (Kilo):

```<182>2016-04-05T01:18:33.296106+00:00 rdo-kilo journal: 2016-04-05 01:18:33.243 1210 INFO keystone.openstack.common.service [-] Started child 2648```

We get something like this:

```<30>2016-04-05T00:37:39.577550+00:00 rsrc-03.c1.lab.solinea.com ceilometer-polling: 2016-04-05 00:37:39.576 22271 INFO ceilometer.agent.manager [-] Polling pollster disk.device.write.bytes in the context of meter_source```

We should have logstash patterns that recognize both formats.  Currently, since we don't recognize the new format, we don't categorize the openstack messages based on the component.  The patterns file is in `docker/goldstone-log/patterns`.  

There is already some logic to analyze the syslog-specific header, so our pattern should really only need to worry about this part of the example message:

```ceilometer-polling: 2016-04-05 00:37:39.576 22271 INFO ceilometer.agent.manager [-] Polling pollster disk.device.write.bytes in the context of meter_source``` 

So, a new pattern for OPENSTACK_RFC5424_MESSAGE would break it down into the following fields:

```
component = ceilometer
subcomponent = polling
timestamp = 2016-04-05 00:37:39.576
pid = 22271
loglevel = INFO
program = ceilometer.agent.manager
request_id_list = -
openstack_message = Polling pollster disk.device.write.bytes in the context of meter_source
```

Once the pattern is developed, the logstash filter that determines the component should be updated to only set the component if it's not already set.  The file that does this processing is `docker/goldstone-log/conf.d/34-filter-opestack-syslog`

**Comment by rsmitty** [comment]
Okay, so this seems to be working mostly as expected I believe. Steve finished up the digging on this yesterday and I was looking through just now. There's basically a new set of patterns to catch the beginning of the new log format. It looks like:
```bash
OPENSTACK_COMPONENT %{WORD:component}-%{WORD:subcomponent}
OPENSTACK_RFC5424_MESSAGE %{OPENSTACK_COMPONENT}: %{OPENSTACK_MESSAGE}
```
where `OPENSTACK_MESSAGE` is the same from the previous "normal" message pattern.

This appears to be working as expected in gstone, or at least lines up with what we were seeing in the Kilo instance. 

Liberty lab:
<img width="1021" alt="screen shot 2016-04-06 at 12 01 31 pm" src="https://cloud.githubusercontent.com/assets/1529818/14324238/fdc81c02-fbf1-11e5-877c-41d39c524bb9.png">

Kilo lab:
<img width="1097" alt="screen shot 2016-04-06 at 12 04 45 pm" src="https://cloud.githubusercontent.com/assets/1529818/14324248/08d86a84-fbf2-11e5-9d7b-d680405bda5b.png">

Does this appear correct to you, @jxstanford?

**Comment by jxstanford** [comment]
@rsmitty looks right to me.  you might confirm that either %WORD goes until whitespace, or that the subcomponent never has a token that causes %WORD to end prematurely (_ comes to mind).   If that's the case, maybe you could find an alternative for %WORD.  I think there might be a %NOTSPACE, but not sure.

Once you think that's resolved, go ahead and commit the change to the patterns file that gets baked into docker container on the liberty_readiness branch.

**Comment by rsmitty** [comment]
One that does seem slightly concerning on the Liberty lab, however, are the logs that come from a component but are not timestamped. They appear to be audits from cinder and nova from what I can tell:

<img width="1126" alt="screen shot 2016-04-06 at 12 26 19 pm" src="https://cloud.githubusercontent.com/assets/1529818/14324495/05519d94-fbf3-11e5-89c1-1d7cb2f44276.png">

<img width="1075" alt="screen shot 2016-04-06 at 12 27 44 pm" src="https://cloud.githubusercontent.com/assets/1529818/14324496/0555c4e6-fbf3-11e5-8206-55f4967e0386.png">

**Comment by jxstanford** [comment]
@rsmitty yeah, how's your regex-fu?  seems like these are an alternate, but valid form of message, so we should handle it.  If you didn't find this: http://grokdebug.herokuapp.com/ already, you want to give it a shot.  Seems like you could still get to one pattern with optional chunks between the `component-subcomponent` and the `message` sections.
