### ISSUE TITLE
resolve any issues with event auditing

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#450]
Goldstone has a data feed coming directly from ceilometer.  We set event_database parameter in ceilometer.conf to send messages directly to our elasticsearch.  In Kilo, we modified quite a bit of config in the various paste files in the projects to ensure that audit data was being generated, and in ceilometer to ensure that it was being handled, then forwarded to our ES.

Something seems to have broken between K and L, and we should figure out what it is.  This might be a combination of:

a) finding a way to monitor the notification bus (check with @jbc0 since he might have a utility for this)
b) assessing configuration changes related to the notification system for each project (maybe it became a default, or a config param was changed)
c) confirming that events are getting to ceilometer
d) confirming that ceilometer is sending them to ES

If you get through d, then it should all be working again :-).  We'll need to have a liberty specific set of config changes documented that we can incorporate with the post install setup procedures.

Might be easier to revert the goldstone changes to the lab liberty cloud, and start from square 1, but up to you.

**Comment by rsmitty** [comment]
I've created a Kibana container running at http://10.10.10.27:5601/ so I should be able to get some viz into what's going on.

Unrelated, but maybe part of what's messed up... I'm seeing some gripes from Ceilometer about not having a `ceilometer_api_audit_map.conf` file. Looks like that file is named in the api-paste.ini file:
```bash
...
[filter:audit]
paste.filter_factory = keystonemiddleware.audit:filter_factory
audit_map_file = /etc/ceilometer/ceilometer_api_audit_map.conf
```

Have you seen this file before? Google-fu isn't helping me much. @steve-wormley maybe you're familiar with this file?

**Comment by jxstanford** [comment]
@rsmitty in our `post_install.py` `_configure_ceilometer` function, we should be pushing that file out as a template.  The template file is in the goldstone-server source at `docker/goldstone-base/config/ceilometer/ceilometer_api_audit_map.conf.template`.  It's possible that it didn't get pushed to this environment, and may be part of the problem that's stopping event flow.  Take a look, maybe place the file manually and see if anything is working better!

**Comment by rsmitty** [comment]
Alright, think I've almost got this guy tracked down. After adding in that audit map file and restarting the API, I needed to then reboot the rest of the services. The one that was especially important was `openstack-ceilometer-notification`. That's the service which handles events. Once that was restarted properly, it began to catch events (after a nova boot) and try to push them to ES. However, now there's an error with the format of the event that was pushed. I'm assuming this is from the event_pipeline.yaml that needs to change or something. Here's the error output from `ceilometer event-list`:

```bash
TransportError(400, u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[Njj-6bhIRWuvljGgN2j_3A][events_2016-04-05][0]: SearchParseException[[events_2016-04-05][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"filtered": {"filter": {"bool": {"must": [{"nested": {"path": "traits", "query": {"filtered": {"filter": {"bool": {"should": [], "must": [{"query": {"query_string": {"query": "project_id: \\"47579d8287c84e3cb7e9ce8e99d11d91\\""}}}, {"query": {"query_string": {"query": "user_id: \\"0b9556b8c07647b08142340da89b0d70\\""}}}]}}}}}}]}}}}}]]]; nested: QueryParsingException[[events_2016-04-05] [nested] nested object under path [traits] is not of nested type]; }{[Njj-6bhIRWuvljGgN2j_3A][events_2016-04-08][0]: SearchParseException[[events_2016-04-08][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query": {"filtered": {"filter": {"bool": {"must": [{"nested": {"path": "traits", "query": {"filtered": {"filter": {"bool": {"should": [], "must": [{"query": {"query_string": {"query": "project_id: \\"47579d8287c84e3cb7e9ce8e99d11d91\\""}}}, {"query": {"query_string": {"query": "user_id: \\"0b9556b8c07647b08142340da89b0d70\\""}}}]}}}}}}]}}}}}]]]; nested: QueryParsingException[[events_2016-04-08] [nested] nested object under path [traits] is not of nested type]; }]') (HTTP 500) (Request-ID: req-37a94782-621f-4e6e-9186-726a19ed7fa3)
```

**Comment by jxstanford** [comment]
To be honest, I've never really used the ceilometer event-list call.  Ceilometer is usually sending to MongoDB, so I'm not sure if what you're seeing is a bug in ceilometer or not, but it looks like events started flowing to Goldstone.  Hurray!

Now we just need to make sure that whatever configuration deltas were required get baked into the ansible scripts for Liberty.

![image](https://cloud.githubusercontent.com/assets/787382/14394629/0a541d7c-fd82-11e5-869e-998f7c921564.png)

**Comment by rsmitty** [comment]
Huh, okay well the trick was ensuring that `/etc/ceilometer/ceilometer_api_audit_map.conf` existed, then a restart of the API to ensure it was online, then a restart of the other ceilometer services. So I'm not certain there's anything to change, assuming that the initial setup occurs as designed.

In the goldstone output though, it appears that the only `action` type was authenticate. Still wondering if we have something going on with the event formatting for the other action types (assuming others have been picked up historically).

**Comment by jxstanford** [comment]
yes, looks like a few types of things are missing.  Could you go through each service and see if you can get additional output?  Example:  nova boot something and see if you get the associated events.  If not, it will be something similar.  There are other map files. Maybe they didn't get placed or have other issues.

**Comment by rsmitty** [comment]
Okay, so it seems that a large portion of this was still the original audit-map issue. After restarting cinder and glance, they are now reporting as expected for events. Nova, however, does not seem to be chiming in. I'll be continuing to dig, but as of right now, there's still not anything to actually *fix*.

**Comment by rsmitty** [comment]
Yeah, this does actually work, it just took me grepping through the notifications log to find "compute" instead of "nova" before I realized I'd been searching for the wrong thing. This all looks like it's checking in as expected to me. In the long run, we'll just need Ansible to lay down the audit-map file and trigger restarts of all of the services afterwards.

**Comment by rsmitty** [comment]
Confirmed that all seemed to wrk by searching for "compute", "network", "cinder", and "glance". Found event entries for all when creating/deleting the respective resources.

**Comment by jxstanford** [comment]
Excellent.  @steve-wormley will be committing some ansible code soon.
