### ISSUE TITLE
create saved searches and alerts for canary feature

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#460]
Need the following alerts and searches for canary:

1) search for testflight records with aggregation to graph elapsed time
2) alert for all canary records with result != true
3) search for testflight with a specific uuid (accept uuid as a parameter)
4) * stretch * alert for canary records over some user provided threshold for elapsed_time

**Comment by vichargrave** [comment]
Closed after pull request https://github.com/Solinea/goldstone-server/pull/465 merged
