### ISSUE TITLE
new alerts not being generated or not making it to client

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#463]
alerts panel is currently using the following url to query for new alerts:
http://localhost:8000/core/alert/?page_size=1000
and after 1000 queries:
http://localhost:8000/core/alert/?page=2&page_size=1000

![image](https://cloud.githubusercontent.com/assets/5633015/14440283/071fe366-ffe4-11e5-8e23-f46a57f1d53e.png)

**Comment by lexjacobs** [comment]
old alerts are populated
![image](https://cloud.githubusercontent.com/assets/5633015/14440396/7eae1e52-ffe4-11e5-9a7b-e34dba2fb191.png)

**Comment by jxstanford** [comment]
Confirmed.  This is related to a logstash pipeline change.  Need to update alert-related searches to look at the full_message field instead of the message_field.  Example:

```
  - model: core.SavedSearch
    pk: de730aab-e0f9-40c7-81c0-4289ddb67e96
    fields:
        name: service status UP
        description: 'one or more services have changed status to UP'
        owner: core
        index_prefix: internal-*
        timestamp_field: 'ingest_time'
        protected: true
        query: '{
   "query": {
      "bool": {
         "must": [
            {
               "match_phrase": {
                  "full_message": {
                     "query": "service status update"
                  }
               }
            },
            {
               "match_phrase": {
                  "full_message": {
                     "query": "to up"
                  }
               }
            }
         ]
      }
   }
}'

```

**Comment by vichargrave** [comment]
Fixed and merged.

**Comment by vichargrave** [comment]
Closing issue.
