### ISSUE TITLE
typo in Saved Searches: Log Browser

### ISSUE THREAD

**Issue by Alicia-Solinea** [Solinea/goldstone-server#469]
In the "Images Uploaded" search, the following text exists:
Log messages indicating that a new Glance images has successfully been uploaded

The text should say:
Log messages indicating that a new Glance image has successfully been uploaded

(ie remove the 's' on images)

**Comment by lexjacobs** [comment]
thank you for the report. the goldstone log browser is just repeating an upstream log message not editable by us.

**Comment by lexjacobs** [comment]
reopening issue and attaching a screenshot of referenced content.

![type](https://cloud.githubusercontent.com/assets/5633015/14501225/285b4558-015a-11e6-9087-
02125e0bfca2.png)

**Comment by jxstanford** [comment]
This is a typo in the SavedSearch description I believe.  Assigning to @vichargrave

**Comment by vichargrave** [comment]
Confirmed.  I'll fix it.

**Comment by vichargrave** [comment]
Fixed and merged.

**Comment by vichargrave** [comment]
Closing issue.
