### ISSUE TITLE
Service Status text is funky

### ISSUE THREAD

**Issue by rsmitty** [Solinea/goldstone-server#479]
Still looking at the GStone snapshot version (Version : 1.0.1-SNAPSHOT.0.g8922853.start_version_1.0.1) we were talking about yesterday, it appears that the Service Status pane is showing some crazy behavior on Firefox and some less weird behavior on Chrome. Seems as if the pane is having trouble dealing with some pretty long host names from the lab. The Chrome one at least wraps the text down below, but looks kind of odd when it extends under the "Service" column.

Firefox:
<img width="753" alt="screen shot 2016-04-14 at 2 56 39 pm" src="https://cloud.githubusercontent.com/assets/1529818/14540116/7470c6b4-0251-11e6-8489-04e11e27b829.png">

Chrome:
<img width="629" alt="screen shot 2016-04-14 at 2 56 48 pm" src="https://cloud.githubusercontent.com/assets/1529818/14540084/55655622-0251-11e6-8a90-e60d78f0c538.png">

**Comment by jxstanford** [comment]
@lexjacobs we may have FQDNs on host names in the service status panel.  Could you adjust the first row of bootstrap to give that panel 5 and the metric stream panel 7?
