### ISSUE TITLE
if all logBrowser filters are deselected, next visit to logBrowser results in an empty set of Log Severity Filters.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#483]
checkbox state survives page view change:

![image](https://cloud.githubusercontent.com/assets/5633015/14543699/4565fc60-024a-11e6-8f30-94446942cf19.png)

...and if you navigate back to the page after having unchecked all of the severity filters this is what you will see:

![image](https://cloud.githubusercontent.com/assets/5633015/14543723/63932c1c-024a-11e6-8329-9e20bb2dd31e.png)

**Comment by lexjacobs** [comment]
suggestions:
* check for accidental global variable leakage (declared without var)
* check for something being connected to the goldstone namespace

**Comment by lexjacobs** [comment]
The global persistence of the filters was not determined, but the more relevant error was handled. Now when we visiting the page after deselecting all filters the filter modal will not be blank.

**Comment by joraldaz** [comment]
And combined with the Issue 360 - 'check all' button in logViewer filter modal now its easier to check all options again
