### ISSUE TITLE
Chart axes and content not resized when browser resizes

### ISSUE THREAD

**Issue by jbc0** [Solinea/goldstone-server#528]
When resizing the browser window the chart borders stretch but the content and axes do not. 
* Waiting for automatic content refresh has no effect.
* Manual browser refresh corrects the problem.

See:
https://drive.google.com/open?id=0ByRjIsefyC_pM2hBUFpFblEteTA

**Comment by lexjacobs** [comment]
In progress: https://css-tricks.com/debouncing-throttling-explained-examples/
