### ISSUE TITLE
"database problems" SavedSearch to broad

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#540]
matches much more than it should.  I suspect some misinterpretation of the boolean "should" clause.  It actually didn't seem to do any filtering of the results

Examples matches:

![image](https://cloud.githubusercontent.com/assets/787382/15052711/cbabe482-12b3-11e6-8c34-f145c695a317.png)

**Comment by vichargrave** [comment]
Closed by PR https://github.com/Solinea/goldstone-server/pull/562.
