### ISSUE TITLE
"image uploaded" SavedSearch does not detect image upload

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#541]
`glance image-create --name 'rdo-kilo' --progress --file ~/devel/images/RDO-kilo-20160204.ova --disk-format vmdk --container-format ova`

does not result in any hits.

**Comment by vichargrave** [comment]
I'm not seeing an error here.  This what I get after uploading an image:

<img width="991" alt="screen shot 2016-05-12 at 6 09 29 pm" src="https://cloud.githubusercontent.com/assets/260028/15235027/b8f28f94-186c-11e6-985d-94da30f342a2.png">

**Comment by jxstanford** [comment]
Go ahead and close with a “can’t reproduce”

**Comment by vichargrave** [comment]
Can't reproduce.
