### ISSUE TITLE
Cinder volume created saved search should search using the "openstack_message" field

### ISSUE THREAD

**Issue by vichargrave** [Solinea/goldstone-server#571]
The cinder volume created saved search searches using the "message" field instead of "openstack_message" field.

**Comment by itlinux** [comment]
In the backend openstack used targetcli to create those volumes for Cinder, maybe that’s another way to pull data out?

Remo

**Comment by vichargrave** [comment]
I'm going to take approach 1 as noted before to get this working.  I want to do testing of our logstash configs under possibly a separate ticket.
